# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Héctor Leopoldo Venegas-Quiñones
title: Hydrogeologyist
email: venegasquinones@gmail.com
website: https://www.linkedin.com/in/venegasquinones7/

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  As a GIS hydrogeologist professional, I have extensive experience in data analysis, GIS, hydrology, geology, flood events, and machine learning. I am dedicated to advancing the academic, public, and private sectors and have contributed to this goal by creating various free tools for the community to improve the stakeholder process. In addition, I have a strong background in groundwater modeling, dewatering systems, fault and vertical displacement detection, and remote sensing, and have successfully applied these skills to various projects. My ability to effectively utilize these tools has enabled me to conduct accurate analyses and create innovative solutions. I am committed to staying up-to-date with the latest developments in GIS hydrogeology and am always seeking new opportunities to learn and grow in my field. My zeal for this profession motivates me to consistently enhance my skills, make meaningful contributions to the scientific community, and resolve issues that impact people.

  <mark>Education</mark>
  The University of Arizona, AZ, United States
  •	PhD (c) – Groundwater – Machine Learning – Remote Sensing
  •	MSc. – Remote Sensing Analysis – Machine Learning
  •	MSc. – Groundwater Modelling – Stakeholder process
  Pontifical Catholic University of Chile, Chile
  •	MSc. – Erosion – Groundwater – Machine Learning
  Andrés Bello University, Chile
  •	Environmental Engineer


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
    title: Development of Groundwater Levels Dataset for Chile
    link: github.com/venegasquinones7
    additional_links:
      - title: venegasquinones7/Groundwater-Dataset-Project
        icon: fab fa-github
        url: github.com/venegasquinones7/Groundwater-Dataset-Project
    quote: >
      This project represents a significant advancement in the field of hydrogeology and water resource management. It sets a new standard for utilizing satellite data and machine learning to estimate groundwater levels.
    description: | 
      I initiated this project to address the lack of unified, quality-controlled groundwater data in Chile. Leveraging satellite data and machine learning, I developed a comprehensive and reliable nationwide groundwater dataset. This project has significantly contributed to sustainable water management practices and has been featured in prominent journals such as Nature Scientific Data and Groundwater Journal. I am proud of the impact this work has had on the scientific community and water management strategies in Chile.
      
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Montgomery & Associates
        link: montgomeryassociates.com
        sub_title: GIS Hydrogeologist
        caption: April 2022 - Present
        quote: >
          Applying advanced GIS and hydrogeology techniques to solve complex groundwater problems and enhance water resource management.
        description: |
          At Montgomery & Associates, I specialize in groundwater modeling using FEFLOW and remote sensing data extraction. I lead a team focused on developing innovative solutions for groundwater management and dewatering systems. My work includes fault and vertical displacement detection, and I am committed to using the latest GIS technologies and machine learning methodologies to drive sustainable water resource management.
      - layout: left
        title: The University of Arizona
        link: arizona.edu
        sub_title: Research Assistant
        caption: January 2021 - Present
        quote: >
          Bridging academia and practical applications to advance hydrology and environmental engineering.
        description: |
          As a Research Assistant at The University of Arizona, I engage in data analysis, machine learning, and GIS for hydrological studies. My research focuses on enhancing aquifer recharge practices and improving flood policy data processing. I also contribute to teaching courses on statistical techniques and remote sensing, fostering the next generation of environmental engineers and hydrologists.
      - layout: left
        title: Call & Nicholas
        link: callnicholas.com
        sub_title: Hydrogeologist
        caption: August 2019 - August 2020
        quote: >
          Pioneering innovative hydrogeological solutions to support mining operations and environmental sustainability.
        description: |
          At Call & Nicholas, I conducted groundwater modeling and remote sensing data analysis to support mining operations. My role involved developing dewatering systems and assessing the impact of mining activities on groundwater resources. I also worked as a soil laboratory technician, providing critical data to guide sustainable mining practices.

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Arizona
        caption: 2021 - Present
        sub_title: PhD (c) in Groundwater - Machine Learning - Remote Sensing
        quote: >
          The University of Arizona is renowned for its research in hydrology and water resources, providing cutting-edge education and opportunities in environmental sciences.
        description: |
          Pursuing my PhD at the University of Arizona has been a transformative experience, where I specialize in deep learning, remote sensing, and data science. My research aims to advance the understanding of groundwater dynamics and contribute to sustainable water management. I also engage in teaching and mentoring, sharing my knowledge and passion for hydrology with undergraduate and graduate students.
      - layout: left
        title: University of Arizona
        caption: 2021 - 2022
        sub_title: MSc in Remote Sensing Analysis - Machine Learning
        quote: >
          Building expertise in the application of remote sensing and machine learning to address environmental challenges and enhance water resource management.
        description: |
          My MSc program focused on leveraging satellite data and machine learning techniques to analyze environmental variables. This education has equipped me with advanced skills in cluster analysis and land index estimation, which I apply in my research to improve water resource management and environmental monitoring.
      - layout: left
        title: University of Arizona
        caption: 2019 - 2020
        sub_title: MSc in Groundwater Modelling - Stakeholder Process
        quote: >
          Developing robust groundwater models to support stakeholder engagement and informed decision-making in water management.
        description: |
          During my MSc program, I specialized in groundwater modeling and the stakeholder process, learning to create accurate and reliable models to inform water management decisions. This experience has strengthened my ability to communicate complex technical information to diverse audiences and work collaboratively with stakeholders to address water resource challenges.
      - layout: left
        title: Pontifical Catholic University of Chile
        caption: 2014 - 2016
        sub_title: MSc in Hydraulic and Environmental Engineering Sciences
        quote: >
          A leading institution in Latin America, known for its rigorous academic programs and research excellence in engineering and environmental sciences.
        description: |
          At the Pontifical Catholic University of Chile, I focused on fluid mechanics, hydraulic engineering, and water resource systems. My research explored soil erosion and water resource impacts using USLE/RUSLE and machine learning, providing a solid foundation for my current work in hydrogeology and environmental engineering.
      - layout: left
        title: Andrés Bello University
        caption: 2008 - 2013
        sub_title: BSc in Environmental Engineering
        quote: >
          Andrés Bello University is recognized for its strong commitment to sustainability and environmental stewardship, offering comprehensive programs in environmental engineering.
        description: |
          My undergraduate studies at Andrés Bello University laid the groundwork for my career in environmental engineering. I graduated at the top of my class, with a thesis focused on hazardous waste management. My involvement in student leadership as President of the student council enriched my academic experience and honed my skills in project management and team collaboration.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Beyond my professional interests in hydrogeology, GIS, and environmental engineering, I have a variety of hobbies and personal interests that keep me balanced and inspired:
      - Hiking and exploring nature
      - Reading scientific literature and staying updated with the latest research
      - Practicing photography, especially landscapes and wildlife
      - Volunteering for environmental conservation projects
      - Cooking and trying out new recipes
      - [Learning new languages](https://www.duolingo.com)
  
      Here's a glimpse of one of my favorite places  
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
